language: node_js
node_js:
  - "0.10"
  - "0.12"
  - iojs
sudo: false
# download test suite and run tests... submodule? meta testing project with
# all of the reference implementations?
script: 
  - npm run test
notifications:
  email:
    on_success: change
    on_failure: change
